pipeline {
    agent any

    environment {
        IMAGE_NAME = "backend-container"
        CONTAINER_NAME = "backend-container"
        PORT = "8080"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend JAR') {
            steps {
                dir('backend/aws-springboot-project') {
                    sh  'mvn clean install -Dmaven.test.skip=true'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/aws-springboot-project') {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh """
                docker stop ${CONTAINER_NAME} || true
                docker rm ${CONTAINER_NAME} || true
                """
            }
        }
        stage('Run Backend Container') {
            steps {
                dir('backend/aws-springboot-project') {
                   sh '''
                   docker run -d \
                   --name backend-container \
                   --env-file .env \
                   --network aws-net \
                   -p 8080:8080 \
                   backend-container:latest
                   '''
                }
            }
        }

    }

    post {
        success {
            echo "✅ Backend deployed successfully"
        }
        failure {
            echo "❌ Backend deployment failed"
        }
    }
}

